variable "dns_support" { default = true }
variable "dns_host" { default = true }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "access" { default = "AKIAUXVOEN7YR763FKT3" }
variable "secret_key" { default = "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" }
variable "region" { default = "us-east-1" }
variable "project" { default = "xcloud-multicloud" }
variable "azn" { default = ["us-east-1a", "us-east-1b", "us-east-1d"] }
variable "cidr_block" { default = ["0.0.0.0/0"] }
variable "azn_cnt" { default = 2}
variable "cidr_vpc" { default = "10.0.0.0/22" }
